# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/mips_5cycle/mips_5cycle.cache/wt [current_project]
set_property parent.project_path C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/mips_5cycle/mips_5cycle.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/86130/Desktop/mips_5cycle/mips_5cycle/mips_5cycle/mips_5cycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/86130/Desktop/mips_5cycle/mips_5cycle/coe/mipstest.coe
read_verilog -library xil_defaultlib {
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/adder.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/alu.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/aludec.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/controller.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/datapath.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/flopenrc.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/flopr.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/floprc.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/hazard.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/instrflopFD.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/maindec.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/mips.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/mux2.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/mux3.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/pcff.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/regfile.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/signext.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/sl2.v
  C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/top.v
}
read_ip -quiet C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet C:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/86130/Desktop/mips_5cycle/mips_5cycle/rtl/ip/inst_mem/inst_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
